apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pdb.yaml

images:
- name: ghcr.io/sogos-llc/mirai-app/mirai-marketing
  newName: ghcr.io/sogos-llc/mirai-app/mirai-marketing
  newTag: 727a844
