apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pdb.yaml
- migration-job.yaml
# stripe-secret.yaml is gitignored - manage manually with kubectl apply

images:
- name: ghcr.io/sogos-llc/mirai-app/mirai-backend
  newName: ghcr.io/sogos-llc/mirai-app/mirai-backend
  newTag: 8811ffc
