apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pdb.yaml

images:
- name: ghcr.io/sogos-llc/mirai-app/mirai-frontend
  newName: ghcr.io/sogos-llc/mirai-app/mirai-frontend
  newTag: 73bcbc0
