apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- redis/redis-deployment.yaml

images:
- name: ghcr.io/sojohnnysaid/mirai-app/mirai-frontend
  newTag: d9f16b5

# namespace managed by platform repo, each resource has namespace set explicitly
# labels already defined in each resource, no need to add via kustomize
