apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- redis/redis-deployment.yaml

images:
- name: ghcr.io/sojohnnysaid/mirai-app/mirai-frontend
  newName: ghcr.io/sojohnnysaid/mirai-prototype/mirai-frontend
  newTag: f1a8d4e

namespace: mirai

commonLabels:
  app.kubernetes.io/name: mirai-frontend
  app.kubernetes.io/part-of: mirai
